Ensure all hdiutil detaches are retried
create-dmg/create-dmg pull request #139
Opened 2022-07-14 23:57 UTC by lukaso

This extends the retry logic to all `hdiutil detach` calls.

2022-07-16 00:26 UTC, pzhlkj6612 requested changes
Hi! Thanks for your work. I have a suggestion for renaming the function you extracted.

2022-07-16 00:26 UTC, pzhlkj6612 commented on create-dmg
> +function hdiutil-detach-retry() {
```diff
- function hdiutil-detach-retry() {
+ function hdiutil_detach_retry() {
```

From my testing, functions with hyphens (or dashes) in their names work in both Bash 3.2.57 on macOS and 5.0.17 on Ubuntu, but I didn't find anywhere in the manual saying it is supported \* . To reduce confusion, I think it is better to use underscores.

\* : the manual says

```console
$ bash --version
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
...

$ man bash
...
DEFINITIONS
       The following definitions are used throughout the rest of this document.
       ...
       name   A word consisting only of alphanumeric characters and underscores, and  beginning  with  an  alphabetic
              character or an underscore.  Also referred to as an identifier.

...

   Shell Function Definitions
       A shell function is an object that is called like a simple command and executes a compound command with a  new  set
       of positional parameters.  Shell functions are declared as follows:

       name () compound-command [redirection]
       function name [()] compound-command [redirection]
              ...

```

2022-07-17 12:27 UTC, Benitoite requested changes
Suggest using underscores also for cross-shell compatibility (`sh` and `csh` do not allow minus in function names)

2022-07-17 12:27 UTC, Benitoite commented on create-dmg
> +	hdiutil-detach-retry "${DEV_NAME}"
In line with 6612's suggestion regarding cross-shell compatible naming with underscores: 
```suggestion
	hdiutil_detach_retry "${DEV_NAME}"
```

2022-07-17 12:27 UTC, Benitoite commented on create-dmg
> +			hdiutil-detach-retry "${DEV_NAME}"
```suggestion
			hdiutil_detach_retry "${DEV_NAME}"
```

2022-07-17 14:08 UTC, pzhlkj6612 commented
Hi @Benitoite .

> Suggest using underscores also for cross-shell compatibility (`sh` and `csh` do not allow minus in function names)

well, we already have the "```#!/usr/bin/env bash```" shebang at the top of the script:

https://github.com/create-dmg/create-dmg/blob/48a4aadb768da76e7903d090f31a2db20c583942/create-dmg#L1

and there are bunch of Bash conditional statements (```if [[ ]]```) in it:

https://github.com/create-dmg/create-dmg/blob/48a4aadb768da76e7903d090f31a2db20c583942/create-dmg#L218-L221

so we *may* have no need to consider the cross-shell compatibility.

Your opinion?

2022-07-17 17:18 UTC, Benitoite commented
Count my vote for the underscore as a preferred style for function names independent of shell choice.

2022-07-19 08:36 UTC, merged

2022-07-20 14:30 UTC, lukaso commented
Thanks!